# Generated by Django 2.1.1 on 2018-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(help_text='Display name of DB connection', max_length=100)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('pg', 'PostgreSQL'), ('mongo', 'MongoDB')], default='mysql', help_text='Type of database', max_length=50)),
                ('db_host', models.CharField(help_text='DB Host', max_length=300)),
                ('db_port', models.IntegerField()),
                ('db_name', models.CharField(help_text='Database name', max_length=100)),
                ('db_username', models.CharField(help_text='Database user name', max_length=100)),
                ('db_password', models.CharField(help_text='Database password', max_length=30)),
                ('ssh_host', models.CharField(help_text='SSH Host', max_length=300)),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_username', models.CharField(help_text='SSH user name', max_length=100)),
                ('ssh_password', models.CharField(blank=True, help_text='SSH password', max_length=30)),
            ],
        ),
    ]
