# Generated by Django 2.1.1 on 2018-10-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the report', max_length=300)),
                ('query', models.TextField(help_text='Database query to generate report')),
            ],
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='db_type',
            field=models.CharField(choices=[('db_mysql', 'MySQL'), ('db_pgsql', 'PostgreSQL'), ('db_oracle', 'Oracle'), ('db_mssql', 'MS SQL'), ('db_sqlite', 'SQLite')], default='mysql', help_text='Type of database', max_length=50),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='SSH Host', max_length=300),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='ssh_port',
            field=models.IntegerField(blank=True, default=22),
        ),
        migrations.AlterField(
            model_name='dbconfig',
            name='ssh_username',
            field=models.CharField(blank=True, help_text='SSH user name', max_length=100),
        ),
    ]
